### ISSUE TITLE
ReferenceError: requestAnimationFrame is not defined

### ISSUE THREAD

**Issue by danielkv** [axeldelafosse/expo-next-monorepo-example#28]
I'm having this problem. I believe it's trying to load in the server side, that's why the error, but not sure how to solve it:

```
ReferenceError: requestAnimationFrame is not defined
    at eval (webpack-internal:///../../node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedNode.js:94:117)
    at Object.../../node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedNode.js (/home/daniel/projects/labook/packages/web/.next/server/pages/_app.js:2050:1)
    at __webpack_require__ (/home/daniel/projects/labook/packages/web/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///../../node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedEvent.js:16:71)
    at Object.../../node_modules/react-native-reanimated/lib/reanimated1/core/AnimatedEvent.js (/home/daniel/projects/labook/packages/web/.next/server/pages/_app.js:2028:1)
    at __webpack_require__ (/home/daniel/projects/labook/packages/web/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///../../node_modules/react-native-reanimated/lib/createAnimatedComponent.js:18:89)
    at Object.../../node_modules/react-native-reanimated/lib/createAnimatedComponent.js (/home/daniel/projects/labook/packages/web/.next/server/pages/_app.js:1797:1)
    at __webpack_require__ (/home/daniel/projects/labook/packages/web/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///../../node_modules/react-native-reanimated/lib/Animated.js:7:82)
```

**Comment by marklawlor** [comment]
You will need to polyfill it https://github.com/axeldelafosse/expo-next-monorepo-example/blob/2ea30635d57b4e3293f34345ba8ea8bf2b4e3329/packages/next/src/pages/_app.tsx#L3

**Comment by danielkv** [comment]
I'm using raf to polyfill, but I'm gonna try a different setup

**Comment by danielkv** [comment]
I did try a different setup but didn't manage to make it work yet:

```tsx
import { FC } from 'react';

import AppWrapper from 'app/app/app.wrapper';
import type { AppProps } from 'next/app';
import 'raf/polyfill';

// @ts-ignore
global.setImmediate = requestAnimationFrame;
import 'setimmediate';

const App: FC<AppProps> = ({ Component, pageProps }) => {
    return (
        <AppWrapper>
            <Component {...pageProps} />
        </AppWrapper>
    );
};

export default App;
```

When I use like this it gives me this error: `TypeError: global.__reanimatedWorkletInit is not a function`

```tsx
import { FC } from 'react';
import 'react-native-reanimated';

import AppWrapper from 'app/app/app.wrapper';
import type { AppProps } from 'next/app';
import 'raf/polyfill';

// @ts-ignore
global.setImmediate = requestAnimationFrame;
import 'setimmediate';

const App: FC<AppProps> = ({ Component, pageProps }) => {
    return (
        <AppWrapper>
            <Component {...pageProps} />
        </AppWrapper>
    );
};

export default App;
```
If I use also `import 'react-native-reanimated';` like above, it gives me this error: `ReferenceError: requestAnimationFrame is not defined`

**Comment by marklawlor** [comment]
It needs to be before the import of react-native-reanimated (or any import that  has react-native-reanimated as a sub dependency).

**Comment by danielkv** [comment]
Trying it here, but it seems to be back to `TypeError: global.__reanimatedWorkletInit is not a function`.

So, now I'm not sure if this error is fixed with `import 'react-native-reanimated'`.

**Comment by danielkv** [comment]
I think I've missed some settings. I did manage to work!
